
name: CI

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run tests
        run: npm run test:ci

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   persist-credentials: false
        #   fetch-depth: 0

      - name: Install
        run: npm install

      - name: Create gh-pages branch if it does not exist
        uses: ChristopherDavenport/create-ghpages-ifnotexists@v1

      - name: Generate docs
        if: github.ref == 'refs/heads/dev'
        run: |
          npm run docs:clean
          npm run docs

      - name: Publish docs to gh-pages
        if: github.ref == 'refs/heads/dev'
        uses: ad-m/github-push-action@master
        with:
          branch: "refs/heads/gh-pages"
          github_token: ${{ github.token }}
          force: true
          directory: docs
